services:
  pretix:
    container_name: pretix
    build:
      dockerfile: Dockerfile
      context: .
    restart: unless-stopped
    depends_on:
      - caddy
      - pretix-db
      - pretix-redis
    volumes:
      - $PWD/pretix/data:/data
      - $PWD/pretix/config/pretix.cfg:/etc/pretix/pretix.cfg
      - $PWD/pretix/config/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - pretix
      - web
  
  pretix-db:
    image: postgres:17
    container_name: pretix-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${PRETIX_DB_NAME}
      - POSTGRES_USER=${PRETIX_DB_USER}
      - POSTGRES_PASSWORD=${PRETIX_DB_PASSWORD}
    volumes:
      - $PWD/pretix/database:/var/lib/postgresql/data
    networks:
      - pretix

  pretix-redis:
    image: redis:latest
    container_name: pretix-redis
    restart: unless-stopped
    networks:
      - pretix

networks:
  pretix:
    external: false
