x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "1m"
    max-file: "1"
    tag: "{{.Name}}"

services:
  caddy:
    logging: *default-logging
  # loki:
  #   logging: *default-logging
  # promtail:
  #   logging: *default-logging
  # grafana:
  #   logging: *default-logging
  