include:
  - ./caddy/docker-compose.yml
  - ./grafana/docker-compose.yml
  - ./loki/docker-compose.yml
  
networks:
  internal:
    external: false
  web:
    external: false
  monitoring:
    external: false