x-logging: &logging
  depends_on:
    - loki
  logging:
    driver: loki
    options:
      loki-url: "http://127.0.0.1:3100/loki/api/v1/push"

services:
  caddy:
    *logging
  caddy-promtail:
    *logging

  hedgedoc:
    *logging
  hedgedoc-db:
    *logging
  
  pretix:
   *logging

  grafana:
    *logging