services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/caddy/config:/config/caddy
      - $PWD/caddy/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/caddy/certs:/data/certs
      - $PWD/caddy/data:/data/caddy
      - $PWD/caddy/logs:/var/log/caddy
    networks:
      - web
      - monitoring
    environment:
      - EMAIL=${CADDY_EMAIL}
      - BASE_DOMAIN=${CADDY_BASE_DOMAIN}
      - GF_SUBDOMAIN=${GF_SUBDOMAIN}
      - HEDGEDOC_SUBDOMAIN=${HEDGEDOC_SUBDOMAIN}
      - PRETIX_SUBDOMAIN=${PRETIX_SUBDOMAIN}
      - TLS_CONFIG=${CADDY_TLS_CONFIG}

  caddy-promtail:
    image: grafana/promtail
    container_name: caddy-promtail
    hostname: caddy-promtail
    restart: unless-stopped
    networks:
      - monitoring
    volumes:
      - $PWD/caddy/promtail-config.yml:/etc/promtail-config.yml
      - $PWD/caddy/logs:/var/log/caddy:ro
    command:
      - '-config.file=/etc/promtail-config.yml'
      - '-config.expand-env=true'